# sidebar:
#   logo:
#     avatar: "[https://cdn.jsdelivr.net/gh/booiris-cdn/img/warlord-helmet.svg](/)"
#   menu:
#     post: "[Blog](/)"
#     wiki: "[Doc](/wiki/)"
#     # notes: "[Notes](/notes/)"
#     game: "[Game](/game/)"
#     about: "[About](/about/)"
#     pic: "[Picture](/pic)"
#   widget_layout:
#     index: [welcome, recent] # for home/wiki/categories/tags/archives/404 pages
#     page: [welcome, toc] # for pages using 'layout:page'
#     post: [toc, repo_info] # for pages using 'layout:post'
#     wiki: [toc, repo_info, wiki_more] # for pages using 'layout:wiki'
#   widgets:
#     home: search, welcome, recent # for home

menubar:
  columns: 4 # ä¸€è¡Œå¤šå°‘ä¸ª
  items: 
    id: post
    title: åšå®¢
    url: /

logo:
  avatar: 'https://cdn.jsdelivr.net/gh/booiris-cdn/img/warlord-helmet.svg' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
  # title: '[{config.title}](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'

article:
  auto_excerpt: 0
  license:
  related_posts:
    enable: false
    title: related article
  # share: [wechat, email, link]


footer:
  social:
    github:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
      url: https://github.com/booiris
    mail:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/a1b00e20f425d.svg"/>'
      url: mailto:booiris02@gmail.com
    steam:
      icon: '<img src="https://cdn.jsdelivr.net/gh/booiris-cdn/img/steam_47012.png"/>'
      url: https://steamcommunity.com/profiles/76561198081152126/
    screep:
      icon: '<img src="https://cdn.jsdelivr.net/gh/booiris-cdn/img/screep.png"/>'
      url: https://screeps.com/a/#!/profile/booiris
    rss:
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-rss" viewBox="0 0 16 16"> <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/> <path d="M5.5 12a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm-3-8.5a1 1 0 0 1 1-1c5.523 0 10 4.477 10 10a1 1 0 1 1-2 0 8 8 0 0 0-8-8 1 1 0 0 1-1-1zm0 4a1 1 0 0 1 1-1 6 6 0 0 1 6 6 1 1 0 1 1-2 0 4 4 0 0 0-4-4 1 1 0 0 1-1-1z"/> </svg>'
      url: https://booiris.space/feed.xml

  # sitemap:
  #   "blog":
  #     - "[recent](/)"
  #     - "[categories](/categories)"
  #     - "[tags](/tags)"
  #     - "[archives](/archives)"
  #   "wiki":
  #     - "[main](/wiki)"
  #     - "[leetcode](/wiki/leetcode)"
  #     - "[redis](/wiki/redis)"
  #     - "[rust_code](/wiki/rust_code)"
  # license: "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
  # source: #'[GitHub](https://github.com/xaoxuu/hexo-theme-stellar)'
  # more: # string or array (support markdown)
  # content: | # æ”¯æŒ Markdown æ ¼å¼
  #   æœ¬ç«™ç”± [@booiris](/) ä½¿ç”¨ [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) ä¸»é¢˜åˆ›å»ºã€‚
  #   æœ¬åšå®¢æ‰€æœ‰æ–‡ç« é™¤ç‰¹åˆ«å£°æ˜å¤–ï¼Œå‡é‡‡ç”¨ [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) è®¸å¯åè®®ï¼Œè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚

copycode:
  enable: true
  js: /js/plugins/copycode.js
  default_text: "Copy" # æŒ‰é’®æ˜¾ç¤ºæ–‡å­—
  success_text: "Copied" # å¤åˆ¶æˆåŠŸä¿¡æ¯

style:
  # font-size:
  #   root: 16px
  #   body: .9375rem # 15px
  #   code: 85% # 14px
  #   codeblock: 0.8125rem # 13px
  font-family:
    logo: 'LXGW WenKai",system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: '"LXGW WenKai",system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    # code: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
    # codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
  # codeblock:
  #   highlightjs_theme: https://gcore.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/styles/atom-one-dark.min.css
  leftbar:
    background: var(--block)
    background-image: 
    blur-px:
    blur-bg:
    # background-image: url(https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.13/image/sidebar-bg1@small.jpg)
    # blur-px: 100px # æ¨¡ç³ŠåŠå¾„
    # blur-bg: var(--alpha60) # æ¨¡ç³Šé¢œè‰²

comments:
  service: beaudar
  beaudar:
    repo: booiris/comment
    branch: master
  comment_title: 'ğŸš§ğŸš§ğŸš§è¯„è®ºåŒºğŸš§ğŸš§ğŸš§'
