# sidebar:
#   logo:
#     avatar: "[https://cdn.jsdelivr.net/gh/booiris-cdn/img/warlord-helmet.svg](/)"
#   menu:
#     post: "[Blog](/)"
#     wiki: "[Doc](/wiki/)"
#     # notes: "[Notes](/notes/)"
#     game: "[Game](/game/)"
#     about: "[About](/about/)"
#     pic: "[Picture](/pic)"
#   widget_layout:
#     index: [welcome, recent] # for home/wiki/categories/tags/archives/404 pages
#     page: [welcome, toc] # for pages using 'layout:page'
#     post: [toc, repo_info] # for pages using 'layout:post'
#     wiki: [toc, repo_info, wiki_more] # for pages using 'layout:wiki'
#   widgets:
#     home: search, welcome, recent # for home

menubar:
  columns: 4 # ä¸€è¡Œå¤šå°‘ä¸ª
  items:
    - id: post
      title: Blog
      url: /
    - id: wiki
      title: Doc
      url: /wiki/
    - id: game
      title: Game
      url: /game
    - id: Picture
      title: Pic
      url: /pic

site_tree:
  # -- åˆ—è¡¨ç±»é¡µé¢ -- #
  # ä¸»é¡µé…ç½®
  home:
    leftbar: welcome, recent
    rightbar: tagcloud, memos
  # åšå®¢åˆ—è¡¨é¡µé…ç½®
  # index_blog:
  #   base_dir: blog # åªå½±å“è‡ªåŠ¨ç”Ÿæˆçš„é¡µé¢è·¯å¾„
  #   menu_id: post # æœªåœ¨ front-matter ä¸­æŒ‡å®š menu_id æ—¶ï¼Œlayout ä¸º post çš„é¡µé¢é»˜è®¤ä½¿ç”¨è¿™é‡Œé…ç½®çš„ menu_id
  #   leftbar: welcome, recent # for categories/tags/archives
  #   rightbar:
  #   nav_tabs:  # è¿‘æœŸå‘å¸ƒ åˆ†ç±» æ ‡ç­¾ ä¸“æ  å½’æ¡£ and ...
  #     # 'æœ‹å‹æ–‡ç« ': /friends/rss/
  # # åšå®¢ä¸“æ åˆ—è¡¨é¡µé…ç½®
  # index_topic:
  #   base_dir: topic # åªå½±å“è‡ªåŠ¨ç”Ÿæˆçš„é¡µé¢è·¯å¾„
  #   menu_id: post # æœªåœ¨ front-matter ä¸­æŒ‡å®š menu_id æ—¶ï¼Œlayout ä¸º topic çš„é¡µé¢é»˜è®¤ä½¿ç”¨è¿™é‡Œé…ç½®çš„ menu_id
  # # æ–‡æ¡£åˆ—è¡¨é¡µé…ç½®
  index_wiki:
    base_dir: wiki # åªå½±å“è‡ªåŠ¨ç”Ÿæˆçš„é¡µé¢è·¯å¾„
    menu_id: wiki # æœªåœ¨ front-matter ä¸­æŒ‡å®š menu_id æ—¶ï¼Œlayout ä¸º wiki çš„é¡µé¢é»˜è®¤ä½¿ç”¨è¿™é‡Œé…ç½®çš„ menu_id
    leftbar: welcome, recent # for wiki
    rightbar: tagcloud, memos
    # nav_tabs:
  #     # 'more': https://github.com/xaoxuu

  Picture:
    base_dir: /pic
    menu_id: Picture
    leftbar: welcome
    rightbar: memos

  # # -- å†…å®¹ç±»é¡µé¢ -- #
  # # åšå®¢æ–‡ç« å†…é¡µé…ç½®
  # post:
  #   menu_id: post # æœªåœ¨ front-matter ä¸­æŒ‡å®š menu_id æ—¶ï¼Œlayout ä¸º post çš„é¡µé¢é»˜è®¤ä½¿ç”¨è¿™é‡Œé…ç½®çš„ menu_id
  #   leftbar: related, recent # for pages using 'layout:post'
  #   rightbar: ghrepo, toc
  # # åšå®¢ä¸“æ æ–‡ç« å†…é¡µé…ç½®
  # topic:
  #   menu_id: post
  # æ–‡æ¡£å†…é¡µé…ç½®
  # wiki:
  #   menu_id: wiki # æœªåœ¨ front-matter ä¸­æŒ‡å®š menu_id æ—¶ï¼Œlayout ä¸º wiki çš„é¡µé¢é»˜è®¤ä½¿ç”¨è¿™é‡Œé…ç½®çš„ menu_id
  #   leftbar: tree, related, recent # for wiki
  #   rightbar: ghrepo, toc
  # ç¬”è®°æœ¬åˆ—è¡¨é¡µé…ç½®
  # notebooks:
  #   base_dir: notebooks # ç¬”è®°æœ¬åˆ—è¡¨é¡µçš„è·¯å¾„ã€‚ä»¥åŠæœªæŒ‡å®š base_dir çš„ç¬”è®°æœ¬çš„è·¯å¾„å‰ç¼€ã€‚
  #   menu_id: notebooks # ç¬”è®°æœ¬åˆ—è¡¨é¡µé«˜äº®çš„ä¸»å¯¼èˆªæ èœå•æŒ‰é’®ã€‚
  #   # ç¬”è®°æœ¬åˆ—è¡¨é¡µçš„å·¦ä¾§æ å’Œå³ä¾§æ ã€‚
  #   leftbar: recent # recent within all notebooks
  #   rightbar: null
  # # ç¬”è®°åˆ—è¡¨é¡µé…ç½®
  # notes:
  #   # ç¬”è®°åˆ—è¡¨é¡µå’Œç¬”è®°é¡µé«˜äº®çš„ä¸»å¯¼èˆªæ èœå•æŒ‰é’®ã€‚
  #   # å¯ä»¥åœ¨ç¬”è®°æœ¬ yaml çš„ menu_id å­—æ®µä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
  #   # å¯ä»¥åœ¨ç¬”è®°çš„ front-matter/menu_id ä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
  #   menu_id: notebooks
  #   # ç¬”è®°åˆ—è¡¨é¡µçš„å·¦ä¾§æ å’Œå³ä¾§æ ã€‚å¯ä»¥åœ¨ç¬”è®°æœ¬ yaml çš„ leftbar å’Œ rightbar å­—æ®µä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
  #   leftbar: tagtree, recent # recent of current notebook
  #   rightbar: null
  # # ç¬”è®°é¡µé…ç½®
  # note:
  #   # ç¬”è®°é¡µçš„å·¦ä¾§æ å’Œå³ä¾§æ 
  #   # å¯ä»¥åœ¨ç¬”è®°æœ¬ yaml çš„ note_leftbar å’Œ note_rightbar å­—æ®µä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
  #   # å¯ä»¥åœ¨ç¬”è®°çš„ front-matter/leftbar å’Œ rightbar å­—æ®µä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
  #   leftbar: tagtree, recent # recent of current notebook
  #   rightbar: toc
  # # ä½œè€…ä¿¡æ¯é…ç½®
  # author:
  #   base_dir: author # åªå½±å“è‡ªåŠ¨ç”Ÿæˆçš„é¡µé¢è·¯å¾„
  #   menu_id: post
  #   leftbar: recent, timeline
  #   rightbar: timeline
  # # é”™è¯¯é¡µé…ç½®
  # error_page:
  #   menu_id: post
  #   '404': '/404.html'
  #   leftbar: recent, timeline
  #   rightbar: timeline
  # # å…¶å®ƒè‡ªå®šä¹‰é¡µé¢é…ç½® layout: page
  # page:
  #   leftbar: recent
  #   rightbar: toc

logo:
  avatar: "https://cdn.jsdelivr.net/gh/booiris-cdn/img/warlord-helmet.svg" # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
  # title: '[{config.title}](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'

article:
  auto_excerpt: 0
  license:
  related_posts:
    enable: false
    title: related article
  # share: [wechat, email, link]

footer:
  social:
    github:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
      url: https://github.com/booiris
    mail:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/a1b00e20f425d.svg"/>'
      url: mailto:booiris02@gmail.com
    steam:
      icon: '<img src="https://cdn.jsdelivr.net/gh/booiris-cdn/img/steam_47012.png"/>'
      url: https://steamcommunity.com/profiles/76561198081152126/
    screep:
      icon: '<img src="https://cdn.jsdelivr.net/gh/booiris-cdn/img/screep.png"/>'
      url: https://screeps.com/a/#!/profile/booiris
    rss:
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-rss" viewBox="0 0 16 16"> <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/> <path d="M5.5 12a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm-3-8.5a1 1 0 0 1 1-1c5.523 0 10 4.477 10 10a1 1 0 1 1-2 0 8 8 0 0 0-8-8 1 1 0 0 1-1-1zm0 4a1 1 0 0 1 1-1 6 6 0 0 1 6 6 1 1 0 1 1-2 0 4 4 0 0 0-4-4 1 1 0 0 1-1-1z"/> </svg>'
      url: https://booiris.space/feed.xml

  # sitemap:
  #   "blog":
  #     - "[recent](/)"
  #     - "[categories](/categories)"
  #     - "[tags](/tags)"
  #     - "[archives](/archives)"
  #   "wiki":
  #     - "[main](/wiki)"
  #     - "[leetcode](/wiki/leetcode)"
  #     - "[redis](/wiki/redis)"
  #     - "[rust_code](/wiki/rust_code)"
  # license: "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
  # source: #'[GitHub](https://github.com/xaoxuu/hexo-theme-stellar)'
  # more: # string or array (support markdown)
  # content: | # æ”¯æŒ Markdown æ ¼å¼
  #   æœ¬ç«™ç”± [@booiris](/) ä½¿ç”¨ [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) ä¸»é¢˜åˆ›å»ºã€‚
  #   æœ¬åšå®¢æ‰€æœ‰æ–‡ç« é™¤ç‰¹åˆ«å£°æ˜å¤–ï¼Œå‡é‡‡ç”¨ [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) è®¸å¯åè®®ï¼Œè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚

copycode:
  enable: true
  js: /js/plugins/copycode.js
  default_text: "Copy" # æŒ‰é’®æ˜¾ç¤ºæ–‡å­—
  success_text: "Copied" # å¤åˆ¶æˆåŠŸä¿¡æ¯

style:
  # font-size:
  #   root: 16px
  #   body: .9375rem # 15px
  #   code: 85% # 14px
  #   codeblock: 0.8125rem # 13px
  font-family:
    logo: 'LXGW WenKai",system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: '"LXGW WenKai",system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    # code: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
    # codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
  # codeblock:
  #   highlightjs_theme: https://gcore.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/styles/atom-one-dark.min.css
  leftbar:
    background: var(--block)
    background-image:
    blur-px:
    blur-bg:

comments:
  service: beaudar
  beaudar:
    repo: booiris/comment
    branch: master
  comment_title: "ğŸ¦»ğŸ¦»ğŸ¦»ğŸ¦»ğŸ¦»ğŸ¦»ğŸ¦»ğŸ¦»"

data_services:
  memos:
    js: /js/memos.js
