sidebar:
  logo:
    avatar: '[https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/avatar/round/3442075.svg](/)' 
  menu:
    post: '[åšå®¢](/)'
    wiki: '[ç¬”è®°](/wiki/)'
    notes: '[ä¾¿ç¬º](/notes/)'
    about: '[å…³äº](/about/)'
  widget_layout:
    index: [welcome, recent] # for home/wiki/categories/tags/archives/404 pages
    page: [welcome, toc] # for pages using 'layout:page'
    post: [toc, repo_info] # for pages using 'layout:post'
    wiki: [toc, repo_info, wiki_more] # for pages using 'layout:wiki'
  widgets:
    # Recent update
    recent:
      layout: recent
      rss: # /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
      fallback: recent # Use a backup widget when toc does not exist.
    # welcome
    welcome:
      layout: markdown
      title: ğŸ’©ğŸ¤¡ğŸ‘¹ğŸ‘ºğŸ‘»ğŸ‘½ğŸ‘¾ğŸ¤–
      content: | # support markdown
        æ–½å·¥ä¸­ã€‚ã€‚ã€‚

article:
  auto_excerpt: 0
  license:

# comments:
#   service: beaudar
#   beaudar:
#     repo: booiris/booiris.github.io
#     branch: master

footer:
  social:
    github:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
      url: https://github.com/booiris
    mail:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/a1b00e20f425d.svg"/>'
      url: mailto:booiris02@gmail.com
    # unsplash:
    #   icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3616429.svg"/>'
    #   url: /
    # comments:
    #   icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/942ebbf1a4b91.svg"/>'
    #   url: /about/#comments
  sitemap:
    # 'åšå®¢':
    #   - '[è¿‘æœŸ](/)'
    #   - '[åˆ†ç±»](/)'
    #   - '[æ ‡ç­¾](/)'
    #   - '[å½’æ¡£](/)'
    # 'é¡¹ç›®':
    #   - '[å¼€æºåº“](/)'
    # 'ç¤¾äº¤':
    #   - '[å‹é“¾](/)'
    #   - '[ç•™è¨€æ¿](/)'
    # 'æ›´å¤š':
    #   - '[å…³äºæœ¬ç«™](/)'
    #   - '[GitHub](/)'
  license: 
  source: #'[GitHub](https://github.com/xaoxuu/hexo-theme-stellar)'
  more: # string or array (support markdown)


plugins:
  mathjax:
    enable: true
    cdn: https://cdn.jsdelivr.net/npm/mathjax@2.7.8/MathJax.js?config=TeX-AMS-MML_HTMLorMML